<a href="https://colab.research.google.com/github/Le2se0hy/XAI_An/blob/main/%EA%B8%B0%EC%B4%88%ED%86%B5%EA%B3%84%EB%9F%89.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [7]:
# ============================================================
# 1. 라이브러리 및 Google Drive 연결
# ============================================================
import pandas as pd
from google.colab import drive
from IPython.display import display

drive.mount('/content/drive', force_remount=True)

# ============================================================
# 2. 데이터 불러오기
# ============================================================
file_path = '/content/drive/MyDrive/Seoul_Aprtment_FINAL.xlsx'
df = pd.read_excel(file_path)

print("원본 데이터 크기:", df.shape)

# 열 이름 공백과 줄바꿈 정리
df.columns = (
    df.columns
    .astype(str)
    .str.replace('\n', ' ', regex=False)
    .str.replace('\r', ' ', regex=False)
    .str.replace(r'\s+', ' ', regex=True)
    .str.strip()
)

print("\n전체 열 이름:")
print(df.columns.tolist())


# ============================================================
# 3. 연도 열 찾기
# ============================================================
year_candidates = ['Year_Sold']

year_col = None

for col in year_candidates:
    if col in df.columns:
        year_col = col
        break

if year_col is None:
    raise ValueError(
        "연도 열을 찾지 못했습니다. 위에 출력된 전체 열 이름을 확인한 후 "
        "year_col = '실제 연도 열 이름'으로 직접 지정하세요."
    )

print("\n사용할 연도 열:", year_col)


# ============================================================
# 4. 분석할 변수
# ============================================================
variables = [
    'Log_Price_per_m2',
    'Size_m2',
    'Floor',
    'Units',
    'Construction_Year',
    'Parking_per_household',
    'max_floor',
    'Log_Dist_Water',
    'Log_Dist_Green',
    'Log_Dist_Subway',
    'Dist_Office',
    'High_School_Count',
    'Academy_Count',
    'Bus_Stop',
    'Population',
    'Old Population',
    'Median Age Population',
    'Young Population',
    'Sex_ratio',
    'Pop. Density',
    'Spring',
    'Fall',
    'Winter',
    'Heating'
]


# ============================================================
# 5. 변수 존재 여부 확인
# ============================================================
existing_variables = [col for col in variables if col in df.columns]
missing_variables = [col for col in variables if col not in df.columns]

if missing_variables:
    print("\n찾지 못한 변수:")
    for col in missing_variables:
        print("-", col)

print("\n분석에 사용되는 변수 수:", len(existing_variables))


# ============================================================
# 6. 숫자형으로 변환
# ============================================================
df[year_col] = pd.to_numeric(df[year_col], errors='coerce')

for col in existing_variables:
    df[col] = pd.to_numeric(
        df[col]
        .astype(str)
        .str.replace(',', '', regex=False)
        .str.strip(),
        errors='coerce'
    )


# ============================================================
# 7. 연도별 기초통계량 함수
# ============================================================
def make_descriptive_stats(data, year):
    year_data = data[data[year_col] == year].copy()

    stats = (
        year_data[existing_variables]
        .agg(['min', 'max', 'mean', 'std'])
        .T
        .reset_index()
    )

    stats.columns = [
        'Variable',
        'Minimum',
        'Maximum',
        'Mean',
        'Standard Deviation'
    ]

    stats.insert(0, 'Year', year)

    numeric_cols = [
        'Minimum',
        'Maximum',
        'Mean',
        'Standard Deviation'
    ]

    stats[numeric_cols] = stats[numeric_cols].round(4)

    print(f"{year}년 데이터 수:", len(year_data))

    return stats


# ============================================================
# 8. 2022년과 2023년 기초통계량 계산
# ============================================================
stats_2022 = make_descriptive_stats(df, 2022)
stats_2023 = make_descriptive_stats(df, 2023)
stats_2024 = make_descriptive_stats(df, 2024)
stats_2025 = make_descriptive_stats(df, 2025)

print("\n2022년 기초통계량")
display(stats_2022)

print("\n2023년 기초통계량")
display(stats_2023)

print("\n2024년 기초통계량")
display(stats_2024)

print("\n2025년 기초통계량")
display(stats_2025)


# ============================================================
# 9. 두 연도를 하나의 표로 결합
# ============================================================
stats_total = pd.concat(
    [stats_2022, stats_2023, stats_2024, stats_2025],
    ignore_index=True
)

print("\n2022년과 2023년 전체 기초통계량")
display(stats_total)


# ============================================================
# 10. Excel로 저장
# ============================================================
output_path = (
    '/content/drive/MyDrive/'
    'Descriptive_Statistics_2022_2023.xlsx'
)

with pd.ExcelWriter(output_path, engine='openpyxl') as writer:
    stats_2022.to_excel(
        writer,
        sheet_name='2022년',
        index=False
    )

    stats_2023.to_excel(
        writer,
        sheet_name='2023년',
        index=False
    )

    stats_total.to_excel(
        writer,
        sheet_name='2022_2023 통합',
        index=False
    )

print("\n저장 완료:", output_path)

Mounted at /content/drive
원본 데이터 크기: (189026, 45)

전체 열 이름:
['Year_Sold', 'Month_Sold', 'Day_Sold', 'Gu_Name', 'Dong', 'Jibun', 'Apartment_Name', 'Full_Address', 'Base_Address', 'Size_m2', 'Floor', 'Construction_Year', 'Price', 'Log_Price_per_m2', 'Longitude', 'Latitude', 'Bus_Stop', 'High_School_Count', 'Academy_Count', 'max_floor', 'Units', 'Parking', 'Heating', 'Parking_per_household', 'matched_network_year', 'park_dist_m', 'Log_Dist_Green', 'matched_park_name', 'water_dist_m', 'Log_Dist_Water', 'matched_water_name', 'subway_dist_m', 'Log_Dist_Subway', 'matched_subway_name', 'Dist_Office', 'matched_office_name', 'Spring', 'Fall', 'Winter', 'Population', 'Sex_ratio', 'Pop. Density', 'Young Population', 'Median Age Population', 'Old Population']

사용할 연도 열: Year_Sold

분석에 사용되는 변수 수: 24
2022년 데이터 수: 12631
2023년 데이터 수: 35418
2024년 데이터 수: 57507
2025년 데이터 수: 83470

2022년 기초통계량

,Year,Variable,Minimum,Maximum,Mean,Standard Deviation
0,2022,Log_Price_per_m2,14.6343,17.8372,16.3263,0.4600
1,2022,Size_m2,11.3300,301.4700,66.5692,38.7849
2,2022,Floor,-1.0000,64.0000,9.3274,6.3173
3,2022,Units,4.0000,9778.0000,835.2240,1142.3796
4,2022,Construction_Year,1967.0000,2022.0000,2004.9595,11.5410
5,2022,Parking_per_household,0.0000,15.9310,1.0855,1.2071
6,2022,max_floor,3.0000,69.0000,17.7874,8.2903
7,2022,Log_Dist_Water,4.0099,8.2706,6.8760,0.6436
8,2022,Log_Dist_Green,3.8733,7.8206,6.0465,0.4983
9,2022,Log_Dist_Subway,4.1637,8.3323,6.6240,0.6369
10,2022,Dist_Office,126.3500,10577.1700,3030.4120,1593.0117
11,2022,High_School_Count,12.0000,65.0000,38.6884,9.4507
12,2022,Academy_Count,0.0000,728.0000,32.6102,43.3068
13,2022,Bus_Stop,0.0000,70.0000,24.3754,10.2889
14,2022,Population,1737.0000,244763.0000,80073.4599,56433.0113
15,2022,Old Population,9.7668,28.9098,16.9642,2.8556
16,2022,Median Age Population,64.9248,87.8420,73.0758,3.2027
17,2022,Young Population,2.3611,21.1871,9.9600,2.8410
18,2022,Sex_ratio,72.0954,156.1947,94.1795,5.3473
19,2022,Pop. Density,1373.9748,42260.7143,20903.4387,8349.8715
20,2022,Spring,0.0000,1.0000,0.4076,0.4914
21,2022,Fall,0.0000,1.0000,0.1561,0.3630
22,2022,Winter,0.0000,1.0000,0.2296,0.4206
23,2022,Heating,0.0000,1.0000,0.8103,0.3921

2023년 기초통계량

,Year,Variable,Minimum,Maximum,Mean,Standard Deviation
0,2023,Log_Price_per_m2,14.5430,18.0202,16.3576,0.4369
1,2023,Size_m2,10.7800,309.7000,74.5133,30.3496
2,2023,Floor,-3.0000,68.0000,9.9700,6.5912
3,2023,Units,5.0000,9778.0000,1206.4147,1247.6272
4,2023,Construction_Year,1961.0000,2023.0000,2003.6088,11.4200
5,2023,Parking_per_household,0.0000,13.8028,1.2241,1.3151
6,2023,max_floor,3.0000,69.0000,20.2928,7.9696
7,2023,Log_Dist_Water,4.0452,8.3594,6.8958,0.6339
8,2023,Log_Dist_Green,3.8733,7.7240,6.0527,0.5069
9,2023,Log_Dist_Subway,3.9012,8.3371,6.6677,0.5843
10,2023,Dist_Office,121.5600,10695.5000,3142.3985,1648.0811
11,2023,High_School_Count,11.0000,65.0000,38.5543,10.0410
12,2023,Academy_Count,0.0000,750.0000,42.3207,58.9570
13,2023,Bus_Stop,0.0000,70.0000,24.2886,10.7506
14,2023,Population,2183.0000,245562.0000,78859.5530,52327.8034
15,2023,Old Population,9.9654,30.0982,17.7407,2.9315
16,2023,Median Age Population,64.2581,87.7099,72.1011,2.8563
17,2023,Young Population,2.0955,21.1697,10.1583,2.7981
18,2023,Sex_ratio,70.3309,155.8387,93.3450,4.6687
19,2023,Pop. Density,1359.5426,41370.0730,21143.4688,8250.2852
20,2023,Spring,0.0000,1.0000,0.2791,0.4485
21,2023,Fall,0.0000,1.0000,0.2213,0.4151
22,2023,Winter,0.0000,1.0000,0.1664,0.3724
23,2023,Heating,0.0000,1.0000,0.7205,0.4488

2024년 기초통계량

,Year,Variable,Minimum,Maximum,Mean,Standard Deviation
0,2024,Log_Price_per_m2,14.6224,18.3292,16.4314,0.4631
1,2024,Size_m2,11.4800,273.9600,76.4499,28.8595
2,2024,Floor,-2.0000,68.0000,9.8788,6.5488
3,2024,Units,4.0000,12032.0000,1129.9070,1180.3754
4,2024,Construction_Year,1965.0000,2024.0000,2003.4123,11.2595
5,2024,Parking_per_household,0.0000,15.9310,1.2116,1.1472
6,2024,max_floor,3.0000,69.0000,20.3672,7.7511
7,2024,Log_Dist_Water,4.0099,8.3535,6.8841,0.6392
8,2024,Log_Dist_Green,3.9591,7.7239,6.0568,0.5056
9,2024,Log_Dist_Subway,3.4404,8.3367,6.6760,0.5800
10,2024,Dist_Office,121.5600,10685.8800,3195.3598,1667.2194
11,2024,High_School_Count,12.0000,65.0000,38.2782,9.5933
12,2024,Academy_Count,0.0000,846.0000,41.1365,52.1087
13,2024,Bus_Stop,0.0000,70.0000,24.2769,10.6615
14,2024,Population,2163.0000,242523.0000,76590.8609,50863.5022
15,2024,Old Population,10.3329,31.7382,18.5112,3.0863
16,2024,Median Age Population,62.9208,87.5551,71.6328,2.9767
17,2024,Young Population,2.0280,20.5634,9.8560,2.8071
18,2024,Sex_ratio,68.9559,158.2355,92.8367,4.5440
19,2024,Pop. Density,1329.8896,41562.7737,21000.2270,8178.6170
20,2024,Spring,0.0000,1.0000,0.2504,0.4332
21,2024,Fall,0.0000,1.0000,0.1853,0.3886
22,2024,Winter,0.0000,1.0000,0.1518,0.3588
23,2024,Heating,0.0000,1.0000,0.7236,0.4472

2025년 기초통계량

,Year,Variable,Minimum,Maximum,Mean,Standard Deviation
0,2025,Log_Price_per_m2,14.4120,18.4777,16.4995,0.4735
1,2025,Size_m2,11.3300,317.3600,76.1760,27.7796
2,2025,Floor,-2.0000,67.0000,9.7401,6.4888
3,2025,Units,5.0000,12032.0000,1098.3997,1124.1100
4,2025,Construction_Year,1968.0000,2025.0000,2003.3688,11.4374
5,2025,Parking_per_household,0.0000,15.9310,1.1653,0.9404
6,2025,max_floor,3.0000,69.0000,20.2329,7.5552
7,2025,Log_Dist_Water,3.6147,8.2248,6.9021,0.6147
8,2025,Log_Dist_Green,3.7507,7.7149,6.0550,0.4942
9,2025,Log_Dist_Subway,3.7626,8.3250,6.6575,0.5251
10,2025,Dist_Office,117.7500,10784.6200,3075.9769,1622.7737
11,2025,High_School_Count,11.0000,65.0000,38.5784,9.6485
12,2025,Academy_Count,0.0000,887.0000,39.9656,49.7037
13,2025,Bus_Stop,0.0000,67.0000,22.0390,9.5075
14,2025,Population,2166.0000,240781.0000,74723.3478,50019.3749
15,2025,Old Population,10.6445,33.6906,19.5171,3.2746
16,2025,Median Age Population,61.3441,87.3670,70.9994,2.9476
17,2025,Young Population,1.9116,19.8264,9.4835,2.8353
18,2025,Sex_ratio,67.2133,156.8043,92.6298,4.8219
19,2025,Pop. Density,1314.4322,51090.7895,21679.0655,8894.6203
20,2025,Spring,0.0000,1.0000,0.2988,0.4578
21,2025,Fall,0.0000,1.0000,0.2572,0.4371
22,2025,Winter,0.0000,1.0000,0.1834,0.3870
23,2025,Heating,0.0000,1.0000,0.7514,0.4322

2022년과 2023년 전체 기초통계량

,Year,Variable,Minimum,Maximum,Mean,Standard Deviation
0,2022,Log_Price_per_m2,14.6343,17.8372,16.3263,0.4600
1,2022,Size_m2,11.3300,301.4700,66.5692,38.7849
2,2022,Floor,-1.0000,64.0000,9.3274,6.3173
3,2022,Units,4.0000,9778.0000,835.2240,1142.3796
4,2022,Construction_Year,1967.0000,2022.0000,2004.9595,11.5410
...,...,...,...,...,...,...
91,2025,Pop. Density,1314.4322,51090.7895,21679.0655,8894.6203
92,2025,Spring,0.0000,1.0000,0.2988,0.4578
93,2025,Fall,0.0000,1.0000,0.2572,0.4371
94,2025,Winter,0.0000,1.0000,0.1834,0.3870
95,2025,Heating,0.0000,1.0000,0.7514,0.4322

저장 완료: /content/drive/MyDrive/Descriptive_Statistics_2022_2023.xlsx

In [6]:
# ============================================================
# 1. 라이브러리 불러오기 및 Google Drive 연결
# ============================================================
import pandas as pd
from google.colab import drive
from IPython.display import display

drive.mount('/content/drive', force_remount=True)


# ============================================================
# 2. 데이터 불러오기
# ============================================================
file_path = '/content/drive/MyDrive/Seoul_Aprtment_FINAL.xlsx'

df = pd.read_excel(file_path)

print("원본 데이터 크기:", df.shape)


# ============================================================
# 3. 열 이름 정리
# ============================================================
df.columns = (
    df.columns
    .astype(str)
    .str.replace('\n', ' ', regex=False)
    .str.replace('\r', ' ', regex=False)
    .str.replace(r'\s+', ' ', regex=True)
    .str.strip()
)

print("\n전체 열 이름")
print(df.columns.tolist())


# ============================================================
# 4. 연도 열 찾기
# ============================================================
year_candidates = ['Year_Sold']

year_col = None

for col in year_candidates:
    if col in df.columns:
        year_col = col
        break

if year_col is None:
    raise ValueError(
        "연도 열을 찾지 못했습니다.\n"
        "출력된 전체 열 이름을 확인한 후 year_col을 직접 지정하세요."
    )

print("\n사용할 연도 열:", year_col)


# ============================================================
# 5. 필요한 열 확인
# ============================================================
required_columns = [
    year_col,
    'Heating',
    'Month_Sold'
]

missing_columns = [
    col for col in required_columns
    if col not in df.columns
]

if missing_columns:
    raise ValueError(
        f"다음 열을 찾지 못했습니다: {missing_columns}"
    )


# ============================================================
# 6. 연도 열 숫자형 변환
# ============================================================
df[year_col] = pd.to_numeric(
    df[year_col],
    errors='coerce'
)


# ============================================================
# 7. Heating 더미변수 생성
# 정확히 '도시가스'인 경우만 1
# 나머지는 모두 0
# ============================================================
heating_clean = (
    df['Heating']
    .fillna('')
    .astype(str)
    .str.strip()
)

df['Heating'] = (
    heating_clean == '도시가스'
).astype(int)


# ============================================================
# 8. month_sold에서 월 추출
# ============================================================
# 3, 4, 5 또는 '3월', '2022-03-01' 형식 모두 고려

month_number = pd.to_numeric(
    df['Month_Sold'],
    errors='coerce'
)

month_from_text = pd.to_numeric(
    df['Month_Sold']
    .astype(str)
    .str.extract(r'(\d{1,2})')[0],
    errors='coerce'
)

month_from_date = pd.to_datetime(
    df['Month_Sold'],
    errors='coerce'
).dt.month

df['_month'] = (
    month_number
    .fillna(month_from_date)
    .fillna(month_from_text)
)


# ============================================================
# 9. 계절 더미변수 생성
# ============================================================
# Spring: 3월, 4월, 5월
df['Spring'] = (
    df['_month'].isin([3, 4, 5])
).astype(int)

# Fall: 9월, 10월, 11월
df['Fall'] = (
    df['_month'].isin([9, 10, 11])
).astype(int)

# Winter: 12월, 1월, 2월
df['Winter'] = (
    df['_month'].isin([12, 1, 2])
).astype(int)


# ============================================================
# 10. 전처리 결과 확인
# ============================================================
print("\nheating 원래 값별 Heating 변환 결과")

heating_check = (
    df.groupby('Heating', dropna=False)['Heating']
    .agg(['count', 'min', 'max', 'mean'])
    .reset_index()
)

display(heating_check)


print("\n월별 계절 더미변수 확인")

month_check = (
    df.groupby('_month', dropna=False)[
        ['Spring', 'Fall', 'Winter']
    ]
    .agg(['count', 'mean'])
)

display(month_check)


# ============================================================
# 11. 기초통계량 계산 함수
# ============================================================
dummy_variables = [
    'Heating',
    'Spring',
    'Fall',
    'Winter'
]

def make_descriptive_stats(data, year):

    year_data = data[
        data[year_col] == year
    ].copy()

    if len(year_data) == 0:
        print(f"{year}년 데이터가 없습니다.")

    stats = (
        year_data[dummy_variables]
        .agg(['min', 'max', 'mean', 'std'])
        .T
        .reset_index()
    )

    stats.columns = [
        'Variable',
        'Minimum',
        'Maximum',
        'Mean',
        'Standard Deviation'
    ]

    stats.insert(0, 'Year', year)

    numeric_columns = [
        'Minimum',
        'Maximum',
        'Mean',
        'Standard Deviation'
    ]

    stats[numeric_columns] = (
        stats[numeric_columns]
        .round(4)
    )

    print(f"{year}년 관측치 수: {len(year_data):,}")

    return stats


# ============================================================
# 12. 2022년과 2023년 기초통계량 계산
# ============================================================
stats_2022_dummy = make_descriptive_stats(
    df,
    2022
)

stats_2023_dummy = make_descriptive_stats(
    df,
    2023
)
stats_2024_dummy = make_descriptive_stats(
    df,
    2024
)
stats_2025_dummy = make_descriptive_stats(
    df,
    2025
)

print("\n2022년 Heating 및 계절 변수 기초통계량")
display(stats_2022_dummy)

print("\n2023년 Heating 및 계절 변수 기초통계량")
display(stats_2023_dummy)

print("\n2024년 Heating 및 계절 변수 기초통계량")
display(stats_2024_dummy)

print("\n2025년 Heating 및 계절 변수 기초통계량")
display(stats_2025_dummy)


# ============================================================
# 13. 두 연도 표 통합
# ============================================================
stats_dummy_total = pd.concat(
    [
        stats_2022_dummy,
        stats_2023_dummy,
        stats_2024_dummy,
        stats_2025_dummy
    ],
    ignore_index=True
)

print("\n2022년 및 2023년 통합 표")
display(stats_dummy_total)


# ============================================================
# 14. Excel 파일로 저장
# ============================================================
output_path = (
    '/content/drive/MyDrive/'
    'Dummy_Descriptive_Statistics_2022_2023.xlsx'
)

with pd.ExcelWriter(
    output_path,
    engine='openpyxl'
) as writer:

    stats_2022_dummy.to_excel(
        writer,
        sheet_name='2022년',
        index=False
    )

    stats_2023_dummy.to_excel(
        writer,
        sheet_name='2023년',
        index=False
    )

    stats_2024_dummy.to_excel(
        writer,
        sheet_name='2024년',
        index=False
    )

    stats_2025_dummy.to_excel(
        writer,
        sheet_name='2025년',
        index=False
    )

    stats_dummy_total.to_excel(
        writer,
        sheet_name='2022_2023 통합',
        index=False
    )

    heating_check.to_excel(
        writer,
        sheet_name='Heating 변환확인',
        index=False
    )


# 임시 월 변수 삭제
df.drop(
    columns=['_month'],
    inplace=True
)

print("\n저장 완료")
print(output_path)

Mounted at /content/drive
원본 데이터 크기: (189026, 45)

전체 열 이름
['Year_Sold', 'Month_Sold', 'Day_Sold', 'Gu_Name', 'Dong', 'Jibun', 'Apartment_Name', 'Full_Address', 'Base_Address', 'Size_m2', 'Floor', 'Construction_Year', 'Price', 'Log_Price_per_m2', 'Longitude', 'Latitude', 'Bus_Stop', 'High_School_Count', 'Academy_Count', 'max_floor', 'Units', 'Parking', 'Heating', 'Parking_per_household', 'matched_network_year', 'park_dist_m', 'Log_Dist_Green', 'matched_park_name', 'water_dist_m', 'Log_Dist_Water', 'matched_water_name', 'subway_dist_m', 'Log_Dist_Subway', 'matched_subway_name', 'Dist_Office', 'matched_office_name', 'Spring', 'Fall', 'Winter', 'Population', 'Sex_ratio', 'Pop. Density', 'Young Population', 'Median Age Population', 'Old Population']

사용할 연도 열: Year_Sold

heating 원래 값별 Heating 변환 결과

   Heating   count  min  max  mean
0        0  189026    0    0   0.0

월별 계절 더미변수 확인

       Spring        Fall      Winter
        count mean  count mean  count mean
_month
1        8898  0.0   8898  0.0   8898  1.0
2       12907  0.0  12907  0.0  12907  1.0
3       19715  1.0  19715  0.0  19715  0.0
4       15528  1.0  15528  0.0  15528  0.0
5       19132  1.0  19132  0.0  19132  0.0
6       25656  0.0  25656  0.0  25656  0.0
7       18278  0.0  18278  0.0  18278  0.0
8       15956  0.0  15956  0.0  15956  0.0
9       16385  0.0  16385  1.0  16385  0.0
10      15816  0.0  15816  1.0  15816  0.0
11       9732  0.0   9732  1.0   9732  0.0
12      11023  0.0  11023  0.0  11023  1.0

2022년 관측치 수: 12,631
2023년 관측치 수: 35,418
2024년 관측치 수: 57,507
2025년 관측치 수: 83,470

2022년 Heating 및 계절 변수 기초통계량

   Year Variable  Minimum  Maximum    Mean  Standard Deviation
0  2022  Heating      0.0      0.0  0.0000              0.0000
1  2022   Spring      0.0      1.0  0.4076              0.4914
2  2022     Fall      0.0      1.0  0.1561              0.3630
3  2022   Winter      0.0      1.0  0.2296              0.4206

2023년 Heating 및 계절 변수 기초통계량

   Year Variable  Minimum  Maximum    Mean  Standard Deviation
0  2023  Heating      0.0      0.0  0.0000              0.0000
1  2023   Spring      0.0      1.0  0.2791              0.4485
2  2023     Fall      0.0      1.0  0.2213              0.4151
3  2023   Winter      0.0      1.0  0.1664              0.3724

2024년 Heating 및 계절 변수 기초통계량

   Year Variable  Minimum  Maximum    Mean  Standard Deviation
0  2024  Heating      0.0      0.0  0.0000              0.0000
1  2024   Spring      0.0      1.0  0.2504              0.4332
2  2024     Fall      0.0      1.0  0.1853              0.3886
3  2024   Winter      0.0      1.0  0.1518              0.3588

2025년 Heating 및 계절 변수 기초통계량

   Year Variable  Minimum  Maximum    Mean  Standard Deviation
0  2025  Heating      0.0      0.0  0.0000              0.0000
1  2025   Spring      0.0      1.0  0.2988              0.4578
2  2025     Fall      0.0      1.0  0.2572              0.4371
3  2025   Winter      0.0      1.0  0.1834              0.3870

2022년 및 2023년 통합 표

    Year Variable  Minimum  Maximum    Mean  Standard Deviation
0   2022  Heating      0.0      0.0  0.0000              0.0000
1   2022   Spring      0.0      1.0  0.4076              0.4914
2   2022     Fall      0.0      1.0  0.1561              0.3630
3   2022   Winter      0.0      1.0  0.2296              0.4206
4   2023  Heating      0.0      0.0  0.0000              0.0000
5   2023   Spring      0.0      1.0  0.2791              0.4485
6   2023     Fall      0.0      1.0  0.2213              0.4151
7   2023   Winter      0.0      1.0  0.1664              0.3724
8   2024  Heating      0.0      0.0  0.0000              0.0000
9   2024   Spring      0.0      1.0  0.2504              0.4332
10  2024     Fall      0.0      1.0  0.1853              0.3886
11  2024   Winter      0.0      1.0  0.1518              0.3588
12  2025  Heating      0.0      0.0  0.0000              0.0000
13  2025   Spring      0.0      1.0  0.2988              0.4578
14  2025     Fall      0.0      1.0  0.2572              0.4371
15  2025   Winter      0.0      1.0  0.1834              0.3870

저장 완료
/content/drive/MyDrive/Dummy_Descriptive_Statistics_2022_2023.xlsx